# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: mcr.microsoft.com/azure-functions/azure-functions/node:2.0
# Command to start on workspace startup
tasks:
  - init: npm install
    command: func start
# Ports to expose on workspace startup (optional)
ports:
  - port: 7071
    onOpen: open-preview
